//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisWCFSVR.HKCSERVICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", ConfigurationName="HKCSERVICE.IHkcInterface")]
    public interface IHkcInterface {
        
        // CODEGEN: 消息 mainRequest 的包装命名空间(http://XInterface.hkcsoft.hkc.com)以后生成的消息协定与默认值(http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        HisWCFSVR.HKCSERVICE.mainResponse main(HisWCFSVR.HKCSERVICE.mainRequest request);
        
        // CODEGEN: 消息 sendToHkcRequest 的包装命名空间(http://XInterface.hkcsoft.hkc.com)以后生成的消息协定与默认值(http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        HisWCFSVR.HKCSERVICE.sendToHkcResponse sendToHkc(HisWCFSVR.HKCSERVICE.sendToHkcRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://XInterface.hkcsoft.hkc.com", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] args;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendToHkc", WrapperNamespace="http://XInterface.hkcsoft.hkc.com", IsWrapped=true)]
    public partial class sendToHkcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string code;
        
        public sendToHkcRequest() {
        }
        
        public sendToHkcRequest(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendToHkcResponse", WrapperNamespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", IsWrapped=true)]
    public partial class sendToHkcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendToHkcReturn;
        
        public sendToHkcResponse() {
        }
        
        public sendToHkcResponse(string sendToHkcReturn) {
            this.sendToHkcReturn = sendToHkcReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHkcInterfaceChannel : HisWCFSVR.HKCSERVICE.IHkcInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HkcInterfaceClient : System.ServiceModel.ClientBase<HisWCFSVR.HKCSERVICE.IHkcInterface>, HisWCFSVR.HKCSERVICE.IHkcInterface {
        
        public HkcInterfaceClient() {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HkcInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HisWCFSVR.HKCSERVICE.mainResponse HisWCFSVR.HKCSERVICE.IHkcInterface.main(HisWCFSVR.HKCSERVICE.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] args) {
            HisWCFSVR.HKCSERVICE.mainRequest inValue = new HisWCFSVR.HKCSERVICE.mainRequest();
            inValue.args = args;
            HisWCFSVR.HKCSERVICE.mainResponse retVal = ((HisWCFSVR.HKCSERVICE.IHkcInterface)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HisWCFSVR.HKCSERVICE.sendToHkcResponse HisWCFSVR.HKCSERVICE.IHkcInterface.sendToHkc(HisWCFSVR.HKCSERVICE.sendToHkcRequest request) {
            return base.Channel.sendToHkc(request);
        }
        
        public string sendToHkc(string code) {
            HisWCFSVR.HKCSERVICE.sendToHkcRequest inValue = new HisWCFSVR.HKCSERVICE.sendToHkcRequest();
            inValue.code = code;
            HisWCFSVR.HKCSERVICE.sendToHkcResponse retVal = ((HisWCFSVR.HKCSERVICE.IHkcInterface)(this)).sendToHkc(inValue);
            return retVal.sendToHkcReturn;
        }
    }
}
