//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSDYY.Biz.LaiDaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LaiDaWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TestResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.TestResponse Test(FSDYY.Biz.LaiDaWebService.TestRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APPOINTMENT_REGISTER", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERResponse APPOINTMENT_REGISTER(FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CANCEL_APPOINTMENT_REGISTER", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERResponse CANCEL_APPOINTMENT_REGISTER(FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HISYY_GetResource", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.HISYY_GetResourceResponse HISYY_GetResource(FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HISYY_Submit", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.HISYY_SubmitResponse HISYY_Submit(FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HISYY_Cancel", ReplyAction="*")]
        FSDYY.Biz.LaiDaWebService.HISYY_CancelResponse HISYY_Cancel(FSDYY.Biz.LaiDaWebService.HISYY_CancelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(FSDYY.Biz.LaiDaWebService.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(FSDYY.Biz.LaiDaWebService.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class APPOINTMENT_REGISTERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="APPOINTMENT_REGISTER", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequestBody Body;
        
        public APPOINTMENT_REGISTERRequest() {
        }
        
        public APPOINTMENT_REGISTERRequest(FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class APPOINTMENT_REGISTERRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public APPOINTMENT_REGISTERRequestBody() {
        }
        
        public APPOINTMENT_REGISTERRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class APPOINTMENT_REGISTERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="APPOINTMENT_REGISTERResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERResponseBody Body;
        
        public APPOINTMENT_REGISTERResponse() {
        }
        
        public APPOINTMENT_REGISTERResponse(FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class APPOINTMENT_REGISTERResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string APPOINTMENT_REGISTERResult;
        
        public APPOINTMENT_REGISTERResponseBody() {
        }
        
        public APPOINTMENT_REGISTERResponseBody(string APPOINTMENT_REGISTERResult) {
            this.APPOINTMENT_REGISTERResult = APPOINTMENT_REGISTERResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CANCEL_APPOINTMENT_REGISTERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CANCEL_APPOINTMENT_REGISTER", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequestBody Body;
        
        public CANCEL_APPOINTMENT_REGISTERRequest() {
        }
        
        public CANCEL_APPOINTMENT_REGISTERRequest(FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CANCEL_APPOINTMENT_REGISTERRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public CANCEL_APPOINTMENT_REGISTERRequestBody() {
        }
        
        public CANCEL_APPOINTMENT_REGISTERRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CANCEL_APPOINTMENT_REGISTERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CANCEL_APPOINTMENT_REGISTERResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERResponseBody Body;
        
        public CANCEL_APPOINTMENT_REGISTERResponse() {
        }
        
        public CANCEL_APPOINTMENT_REGISTERResponse(FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CANCEL_APPOINTMENT_REGISTERResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CANCEL_APPOINTMENT_REGISTERResult;
        
        public CANCEL_APPOINTMENT_REGISTERResponseBody() {
        }
        
        public CANCEL_APPOINTMENT_REGISTERResponseBody(string CANCEL_APPOINTMENT_REGISTERResult) {
            this.CANCEL_APPOINTMENT_REGISTERResult = CANCEL_APPOINTMENT_REGISTERResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_GetResourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_GetResource", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequestBody Body;
        
        public HISYY_GetResourceRequest() {
        }
        
        public HISYY_GetResourceRequest(FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_GetResourceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public HISYY_GetResourceRequestBody() {
        }
        
        public HISYY_GetResourceRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_GetResourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_GetResourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_GetResourceResponseBody Body;
        
        public HISYY_GetResourceResponse() {
        }
        
        public HISYY_GetResourceResponse(FSDYY.Biz.LaiDaWebService.HISYY_GetResourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_GetResourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object HISYY_GetResourceResult;
        
        public HISYY_GetResourceResponseBody() {
        }
        
        public HISYY_GetResourceResponseBody(object HISYY_GetResourceResult) {
            this.HISYY_GetResourceResult = HISYY_GetResourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_Submit", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequestBody Body;
        
        public HISYY_SubmitRequest() {
        }
        
        public HISYY_SubmitRequest(FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public HISYY_SubmitRequestBody() {
        }
        
        public HISYY_SubmitRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_SubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_SubmitResponseBody Body;
        
        public HISYY_SubmitResponse() {
        }
        
        public HISYY_SubmitResponse(FSDYY.Biz.LaiDaWebService.HISYY_SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object HISYY_SubmitResult;
        
        public HISYY_SubmitResponseBody() {
        }
        
        public HISYY_SubmitResponseBody(object HISYY_SubmitResult) {
            this.HISYY_SubmitResult = HISYY_SubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_Cancel", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_CancelRequestBody Body;
        
        public HISYY_CancelRequest() {
        }
        
        public HISYY_CancelRequest(FSDYY.Biz.LaiDaWebService.HISYY_CancelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_CancelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public HISYY_CancelRequestBody() {
        }
        
        public HISYY_CancelRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HISYY_CancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HISYY_CancelResponse", Namespace="http://tempuri.org/", Order=0)]
        public FSDYY.Biz.LaiDaWebService.HISYY_CancelResponseBody Body;
        
        public HISYY_CancelResponse() {
        }
        
        public HISYY_CancelResponse(FSDYY.Biz.LaiDaWebService.HISYY_CancelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HISYY_CancelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object HISYY_CancelResult;
        
        public HISYY_CancelResponseBody() {
        }
        
        public HISYY_CancelResponseBody(object HISYY_CancelResult) {
            this.HISYY_CancelResult = HISYY_CancelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : FSDYY.Biz.LaiDaWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<FSDYY.Biz.LaiDaWebService.WebServiceSoap>, FSDYY.Biz.LaiDaWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.TestResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.Test(FSDYY.Biz.LaiDaWebService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            FSDYY.Biz.LaiDaWebService.TestRequest inValue = new FSDYY.Biz.LaiDaWebService.TestRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.TestRequestBody();
            FSDYY.Biz.LaiDaWebService.TestResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.APPOINTMENT_REGISTER(FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequest request) {
            return base.Channel.APPOINTMENT_REGISTER(request);
        }
        
        public string APPOINTMENT_REGISTER(string xml) {
            FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequest inValue = new FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERRequestBody();
            inValue.Body.xml = xml;
            FSDYY.Biz.LaiDaWebService.APPOINTMENT_REGISTERResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).APPOINTMENT_REGISTER(inValue);
            return retVal.Body.APPOINTMENT_REGISTERResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.CANCEL_APPOINTMENT_REGISTER(FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequest request) {
            return base.Channel.CANCEL_APPOINTMENT_REGISTER(request);
        }
        
        public string CANCEL_APPOINTMENT_REGISTER(string xml) {
            FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequest inValue = new FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERRequestBody();
            inValue.Body.xml = xml;
            FSDYY.Biz.LaiDaWebService.CANCEL_APPOINTMENT_REGISTERResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).CANCEL_APPOINTMENT_REGISTER(inValue);
            return retVal.Body.CANCEL_APPOINTMENT_REGISTERResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.HISYY_GetResourceResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.HISYY_GetResource(FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequest request) {
            return base.Channel.HISYY_GetResource(request);
        }
        
        public object HISYY_GetResource(string xml) {
            FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequest inValue = new FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.HISYY_GetResourceRequestBody();
            inValue.Body.xml = xml;
            FSDYY.Biz.LaiDaWebService.HISYY_GetResourceResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).HISYY_GetResource(inValue);
            return retVal.Body.HISYY_GetResourceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.HISYY_SubmitResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.HISYY_Submit(FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequest request) {
            return base.Channel.HISYY_Submit(request);
        }
        
        public object HISYY_Submit(string xml) {
            FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequest inValue = new FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.HISYY_SubmitRequestBody();
            inValue.Body.xml = xml;
            FSDYY.Biz.LaiDaWebService.HISYY_SubmitResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).HISYY_Submit(inValue);
            return retVal.Body.HISYY_SubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSDYY.Biz.LaiDaWebService.HISYY_CancelResponse FSDYY.Biz.LaiDaWebService.WebServiceSoap.HISYY_Cancel(FSDYY.Biz.LaiDaWebService.HISYY_CancelRequest request) {
            return base.Channel.HISYY_Cancel(request);
        }
        
        public object HISYY_Cancel(string xml) {
            FSDYY.Biz.LaiDaWebService.HISYY_CancelRequest inValue = new FSDYY.Biz.LaiDaWebService.HISYY_CancelRequest();
            inValue.Body = new FSDYY.Biz.LaiDaWebService.HISYY_CancelRequestBody();
            inValue.Body.xml = xml;
            FSDYY.Biz.LaiDaWebService.HISYY_CancelResponse retVal = ((FSDYY.Biz.LaiDaWebService.WebServiceSoap)(this)).HISYY_Cancel(inValue);
            return retVal.Body.HISYY_CancelResult;
        }
    }
}
