//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.2012
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUTOSERVICES.Biz.DR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.server.dr.bsoft.com", ConfigurationName="DR.drServicePortType")]
    public interface drServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:execute", ReplyAction="urn:executeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AUTOSERVICES.Biz.DR.executeResponse execute(AUTOSERVICES.Biz.DR.executeRequest request);
        
        // CODEGEN: 操作 echo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:echo", ReplyAction="urn:echoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AUTOSERVICES.Biz.DR.echoResponse echo(AUTOSERVICES.Biz.DR.echoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://ws.server.dr.bsoft.com", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.server.dr.bsoft.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string arg;
        
        public executeRequest() {
        }
        
        public executeRequest(string arg) {
            this.arg = arg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://ws.server.dr.bsoft.com", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.server.dr.bsoft.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public executeResponse() {
        }
        
        public executeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoRequest {
        
        public echoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoResponse {
        
        public echoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface drServicePortTypeChannel : AUTOSERVICES.Biz.DR.drServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class drServicePortTypeClient : System.ServiceModel.ClientBase<AUTOSERVICES.Biz.DR.drServicePortType>, AUTOSERVICES.Biz.DR.drServicePortType {
        
        public drServicePortTypeClient() {
        }
        
        public drServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public drServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public drServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public drServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AUTOSERVICES.Biz.DR.executeResponse AUTOSERVICES.Biz.DR.drServicePortType.execute(AUTOSERVICES.Biz.DR.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public string execute(string arg) {
            AUTOSERVICES.Biz.DR.executeRequest inValue = new AUTOSERVICES.Biz.DR.executeRequest();
            inValue.arg = arg;
            AUTOSERVICES.Biz.DR.executeResponse retVal = ((AUTOSERVICES.Biz.DR.drServicePortType)(this)).execute(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AUTOSERVICES.Biz.DR.echoResponse AUTOSERVICES.Biz.DR.drServicePortType.echo(AUTOSERVICES.Biz.DR.echoRequest request) {
            return base.Channel.echo(request);
        }
        
        public void echo() {
            AUTOSERVICES.Biz.DR.echoRequest inValue = new AUTOSERVICES.Biz.DR.echoRequest();
            AUTOSERVICES.Biz.DR.echoResponse retVal = ((AUTOSERVICES.Biz.DR.drServicePortType)(this)).echo(inValue);
        }
    }
}
