//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisClient.yhszz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="yhszz.MediHisSoap")]
    public interface MediHisSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HisClient.yhszz.HelloWorldResponse HelloWorld(HisClient.yhszz.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TradeType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunService", ReplyAction="*")]
        HisClient.yhszz.RunServiceResponse RunService(HisClient.yhszz.RunServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HisClient.yhszz.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HisClient.yhszz.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HisClient.yhszz.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HisClient.yhszz.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunService", Namespace="http://tempuri.org/", Order=0)]
        public HisClient.yhszz.RunServiceRequestBody Body;
        
        public RunServiceRequest() {
        }
        
        public RunServiceRequest(HisClient.yhszz.RunServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TradeType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TradeMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TradeMsgOut;
        
        public RunServiceRequestBody() {
        }
        
        public RunServiceRequestBody(string TradeType, string TradeMsg, string TradeMsgOut) {
            this.TradeType = TradeType;
            this.TradeMsg = TradeMsg;
            this.TradeMsgOut = TradeMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public HisClient.yhszz.RunServiceResponseBody Body;
        
        public RunServiceResponse() {
        }
        
        public RunServiceResponse(HisClient.yhszz.RunServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RunServiceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TradeMsgOut;
        
        public RunServiceResponseBody() {
        }
        
        public RunServiceResponseBody(int RunServiceResult, string TradeMsgOut) {
            this.RunServiceResult = RunServiceResult;
            this.TradeMsgOut = TradeMsgOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MediHisSoapChannel : HisClient.yhszz.MediHisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediHisSoapClient : System.ServiceModel.ClientBase<HisClient.yhszz.MediHisSoap>, HisClient.yhszz.MediHisSoap {
        
        public MediHisSoapClient() {
        }
        
        public MediHisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediHisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediHisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediHisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HisClient.yhszz.HelloWorldResponse HisClient.yhszz.MediHisSoap.HelloWorld(HisClient.yhszz.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HisClient.yhszz.HelloWorldRequest inValue = new HisClient.yhszz.HelloWorldRequest();
            inValue.Body = new HisClient.yhszz.HelloWorldRequestBody();
            HisClient.yhszz.HelloWorldResponse retVal = ((HisClient.yhszz.MediHisSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HisClient.yhszz.RunServiceResponse HisClient.yhszz.MediHisSoap.RunService(HisClient.yhszz.RunServiceRequest request) {
            return base.Channel.RunService(request);
        }
        
        public int RunService(string TradeType, string TradeMsg, ref string TradeMsgOut) {
            HisClient.yhszz.RunServiceRequest inValue = new HisClient.yhszz.RunServiceRequest();
            inValue.Body = new HisClient.yhszz.RunServiceRequestBody();
            inValue.Body.TradeType = TradeType;
            inValue.Body.TradeMsg = TradeMsg;
            inValue.Body.TradeMsgOut = TradeMsgOut;
            HisClient.yhszz.RunServiceResponse retVal = ((HisClient.yhszz.MediHisSoap)(this)).RunService(inValue);
            TradeMsgOut = retVal.Body.TradeMsgOut;
            return retVal.Body.RunServiceResult;
        }
    }
}
