//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKC.Biz.HKCSERVICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", ConfigurationName="HKCSERVICE.IHkcInterface")]
    public interface IHkcInterface {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://XInterface.hkcsoft.hkc.com) of message mainRequest does not match the default value (http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        HKC.Biz.HKCSERVICE.mainResponse main(HKC.Biz.HKCSERVICE.mainRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://XInterface.hkcsoft.hkc.com) of message sendToHkcRequest does not match the default value (http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        HKC.Biz.HKCSERVICE.sendToHkcResponse sendToHkc(HKC.Biz.HKCSERVICE.sendToHkcRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://XInterface.hkcsoft.hkc.com", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] args;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendToHkc", WrapperNamespace="http://XInterface.hkcsoft.hkc.com", IsWrapped=true)]
    public partial class sendToHkcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string code;
        
        public sendToHkcRequest() {
        }
        
        public sendToHkcRequest(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendToHkcResponse", WrapperNamespace="http://166.1.2.59:8080/HkcZnpf/services/IHkcInterface", IsWrapped=true)]
    public partial class sendToHkcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendToHkcReturn;
        
        public sendToHkcResponse() {
        }
        
        public sendToHkcResponse(string sendToHkcReturn) {
            this.sendToHkcReturn = sendToHkcReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHkcInterfaceChannel : HKC.Biz.HKCSERVICE.IHkcInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HkcInterfaceClient : System.ServiceModel.ClientBase<HKC.Biz.HKCSERVICE.IHkcInterface>, HKC.Biz.HKCSERVICE.IHkcInterface {
        
        public HkcInterfaceClient() {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HkcInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HkcInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HKC.Biz.HKCSERVICE.mainResponse HKC.Biz.HKCSERVICE.IHkcInterface.main(HKC.Biz.HKCSERVICE.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] args) {
            HKC.Biz.HKCSERVICE.mainRequest inValue = new HKC.Biz.HKCSERVICE.mainRequest();
            inValue.args = args;
            HKC.Biz.HKCSERVICE.mainResponse retVal = ((HKC.Biz.HKCSERVICE.IHkcInterface)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HKC.Biz.HKCSERVICE.sendToHkcResponse HKC.Biz.HKCSERVICE.IHkcInterface.sendToHkc(HKC.Biz.HKCSERVICE.sendToHkcRequest request) {
            return base.Channel.sendToHkc(request);
        }
        
        public string sendToHkc(string code) {
            HKC.Biz.HKCSERVICE.sendToHkcRequest inValue = new HKC.Biz.HKCSERVICE.sendToHkcRequest();
            inValue.code = code;
            HKC.Biz.HKCSERVICE.sendToHkcResponse retVal = ((HKC.Biz.HKCSERVICE.IHkcInterface)(this)).sendToHkc(inValue);
            return retVal.sendToHkcReturn;
        }
    }
}
