//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisWCFSVR.YuHangYY {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YuHangYY.IHisApplay")]
    public interface IHisApplay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisApplay/RunService", ReplyAction="http://tempuri.org/IHisApplay/RunServiceResponse")]
        int RunService(string TradeType, string TradeMsg, ref string TradeMsgOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisApplay/PCall", ReplyAction="http://tempuri.org/IHisApplay/PCallResponse")]
        System.DateTime PCall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHisApplay/sendToHis", ReplyAction="http://tempuri.org/IHisApplay/sendToHisResponse")]
        string sendToHis(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHisApplayChannel : HisWCFSVR.YuHangYY.IHisApplay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HisApplayClient : System.ServiceModel.ClientBase<HisWCFSVR.YuHangYY.IHisApplay>, HisWCFSVR.YuHangYY.IHisApplay {
        
        public HisApplayClient() {
        }
        
        public HisApplayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HisApplayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisApplayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisApplayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RunService(string TradeType, string TradeMsg, ref string TradeMsgOut) {
            return base.Channel.RunService(TradeType, TradeMsg, ref TradeMsgOut);
        }
        
        public System.DateTime PCall() {
            return base.Channel.PCall();
        }
        
        public string sendToHis(string code) {
            return base.Channel.sendToHis(code);
        }
    }
}
